### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mrtaz77** [mrtaz77/BDStokz#5]
1. Add a link for starring the repo at the end of the README.md so that the repo will be starred by clicking it.
For instance :
⭐<a class="github-button" href="https://github.com/hmasum52/hmasum52" data-color-scheme="no-preference: dark; light: dark; dark: dark;" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star hmasum52/hmasum52 on GitHub">Star this repository</a>
in masum vai's repo

2. Add logoWithTxt at start of README.md.
3.Add yt tutorial at start.

**Comment by 3m09** [comment]
Issue solved
